### ISSUE TITLE
Add Python bindings

### ISSUE THREAD

**Issue by kalzoo** [rigetti/qcs-sdk-rust#135]
Alongside the C bindings, this repository can build and publish bindings for other languages. If Python bindings are published to PyPI, `pyQuil` can depend on those, allowing for code reuse and less duplicated work between the two SDKs.

Other Benefits:

* The Python gRPC story is not great, with a choice between ugly code generated by the Google first-party library and slow code generated by `betterproto`. This approach lets us use fast-and-decently-user-friendly Rust gRPC code generation instead and bypass that decision altogether.

Package name: `qcs-sdk-python`

**Comment by kalzoo** [comment]
This work can precede the gRPC integration work and rely on the `rpcq` code today; the Python API may not differ between the two.

**Comment by notmgsk** [comment]
- [ ] Restructure project to include to crates `./crates/{lib,python}`?
- [ ] If we're restructuring, should we include the [C-bindings](https://github.com/rigetti/qcs-sdk-c) as a crate too?

**Comment by notmgsk** [comment]
The high-level interface to qcs-sdk-rust is:
* `Executable`: data about a program, e.g. the program itself, number of shots, parameters, etc.
    * `execute_on_qvm`: execute the program on the configured QVM
    * `execute_on_qpu`: compile and execute the program on the configured QPU, and return the results of execution
* `Execution`: execution-related data, e.g. the quantum processor ID, the buffer names, the {rpcq,grpc} client, etc.
* `crate::qpu::translation::translate`: translate an _native_ quil program into an encrypted binary.
* `crate::qpu::quilc::compile_program`: compile a program with quilc into a _native_ program.

Using pyQuil as a reference, a bare-bones API would need to support at least:
* Compiling a Quil program with Quilc: e.g. `qcs_sdk.compile(program_str: str) -> qcs_sdk.Executable` (using `crate::qpu::quilc::compile_program`)
* Translating a native Quil program to an encrypted program object: e.g. `qcs_sdk.translate(compiled_program: qcs_sdk.Executable) -> qcs_sdk.EncryptedExecutable` (using `crate::qpu::translation::translate`)
* Execution against both QVM and QPU: e.g. `qcs_sdk.execute_on_qpu(executable: qcs_sdk.EncryptedExecutable, config: QpuConfiguration) -> qcs_sdk.ExecutionResults` (with `execute_on_qvm` or `execute_on_qpu`).

I think we want to avoid exposing the arithmetic rewriting stuff, per this comment
> It extends some of pyQuil's tech debt, including pyQuil's use of the problematic rewrite_arithmetic further into the future, when it really should be moved into the service
from [this pyQuil issue](https://github.com/rigetti/pyquil/issues/1467).

**Comment by notmgsk** [comment]
Just to reiterate what Kalan said above: we intend to swap out the RPCQ client for a gRPC client, so the API should have no direct dependence on RPCQ (the Python user is uninterested in the underlying communication layer, and is unaffected when it changes).

**Comment by notmgsk** [comment]
From conversation:

> How much of the SDK do we expect pyQuil to use?

Obviously we will be using the networking part to facilitate communication with quilc/qvm/QPUs. But do we want e.g. pyQuil's `Program` object to be replaced by the SDK's `Executable` type? If yes, that's a fairly large rewrite of pyQuil. If no, then we will be doing lots of conversion between pyQuil's types and the SDK's types.

**Comment by notmgsk** [comment]
From conversation:

> Do we intend to wholly supersede pyQuil with the SDK?

**Comment by notmgsk** [comment]
From conversation:

> Given the motivation for this work is to eventually switch out RPCQ for gRPC, should be focus solely on the networking part? (i.e. the above questions RE extensive API usage is irrelevant)

**Comment by notmgsk** [comment]
From conversation:

> Can engagement go away?

**Comment by notmgsk** [comment]
We have the first version of the Python bindings available. There's going to be a second pass which will change a lot of the stuff we have now, so closing this in favor of a separate follow-on issue.
