### ISSUE TITLE
Add timeout to diagnostics

### ISSUE THREAD

**Issue by jselig-rigetti** [rigetti/qcs-sdk-rust#385]
https://github.com/rigetti/qcs-sdk-rust/blob/main/crates/lib/src/diagnostics.rs operations will hang indefinitely if requests hang indefinitely.

We should add a reasonable timeout (perhaps configurable) so that after the timeout, the diagnostics return a report indicating a connection failure due to timeout.

**Comment by notmgsk** [comment]
Closed by #390
